--- # devspaces.yml
name: pmd
description:  Development environment for PMD

# If you want to use a different Dockerfile for your DevSpace, provide the path
# here.
docker-file: Dockerfile

# If you need additional files when building your Dockerfile, such as some
# application binaries that your Dockerfile references, list the glob paths to
# include here. They are relative to this devspaces.yml file.
docker-build-includes: |
  **/*

# generic `build` filter cannot be used once we have a source package named `build`.
sync-ignore: |
  .git
  **/node_modules
  **/target

  .project
  .classpath
  .checkstyle
  .pmd
  .ruleset
  .settings/
  *.iml
  .idea
  *.patch
  */src/site/site.xml
  pmd-core/dependency-reduced-pom.xml
  .bundle
  vendor
