FROM azul/zulu-openjdk:11

LABEL \
    "com.trilogy.company"="aurea" \
    "com.trilogy.team"="devspacesimport" \
    "com.trilogy.product"="PMD" \
    "com.trilogy.stage"="dev" \
    "com.trilogy.maintainer.skype"="ragnarokkrr" \
    "com.trilogy.maintainer.email"="nilseu.junior@aurea.com" \
    "maintainer"="Nilseu Padilha <nilseu.junior@aurea.com>" \
    "description"="This file generates a docker image containing all the dependencies and tools for PMD project build."

WORKDIR /data

ENTRYPOINT tail -f /dev/null
